from http.server import BaseHTTPRequestHandler, HTTPServer
from urllib.parse import urlparse
from urllib.parse import parse_qs

import Run
from PyInfoFiles import Variables

hostName = "localhost"
serverPort = 8080


class MyServer(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header("Content-type", "text/html")
        self.end_headers()
        self.wfile.write(bytes("<html><head><title>PyMiner</title></head>", "utf-8"))
        self.wfile.write(bytes("<p>Request: %s</p>" % self.path, "utf-8"))
        self.wfile.write(bytes("<body>", "utf-8"))
        self.wfile.write(bytes("<p>Player Data:</p>", "utf-8"))
        self.wfile.write(bytes("</body></html>", "utf-8"))
        query_components = parse_qs(urlparse(self.path).query)
        if 'posX' in query_components:
            Variables.posX = query_components["posX"][0]
            Run.commands()
        if 'posY' in query_components:
            Variables.posY = query_components["posY"][0]
            Run.commands()
        if 'posZ' in query_components:
            Variables.posZ = query_components["posZ"][0]
            Run.commands()

        positionX = f"<html><head></head><body><h1>Current Player X: {Variables.posX}</h1></body></html>"
        positionY = f"<html><head></head><body><h1>Current Player Y: {Variables.posY}</h1></body></html>"
        positionZ = f"<html><head></head><body><h1>Current Player Z: {Variables.posZ}</h1></body></html>"
        # Some custom HTML code, possibly generated by another function
        # Writing the HTML contents with UTF-8
        self.wfile.write(bytes(positionX, "utf8"))
        self.wfile.write(bytes(positionY, "utf8"))
        self.wfile.write(bytes(positionZ, "utf8"))


if __name__ == "__main__":
    webServer = HTTPServer((hostName, serverPort), MyServer)
    print("Server started http://%s:%s" % (hostName, serverPort))

    try:
        webServer.serve_forever()
    except KeyboardInterrupt:
        pass

    webServer.server_close()
    print("Server stopped.")
